//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public string MaPhong { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
        public Nullable<int> MaLoaiPhong { get; set; }
        public Nullable<int> MaDonDep { get; set; }
    }
}
